name: GitHub Pages Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install  # Change this if you are using a different package manager

    - name: Build the site
      run: npm run build  # Adjust this to your build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust this to your build output directory

  report-build-status:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
    - name: Report build status
      run: echo "Build and deployment were successful!"  # Customize this step as needed
